// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyi9HRlH19Shmhw0Zno-mFl9Q1OlFP86Y',
    appId: '1:15051457497:web:359c048d7dfb2649d34fc8',
    messagingSenderId: '15051457497',
    projectId: 'flutter-project-01-589db',
    authDomain: 'flutter-project-01-589db.firebaseapp.com',
    databaseURL: 'https://flutter-project-01-589db-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-01-589db.appspot.com',
    measurementId: 'G-G3RSHTJQWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqB8prvai5bYncgz1vfIt3BKRgz2LUDGs',
    appId: '1:15051457497:android:117c4adf2db8d1c5d34fc8',
    messagingSenderId: '15051457497',
    projectId: 'flutter-project-01-589db',
    databaseURL: 'https://flutter-project-01-589db-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-01-589db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbbaDq7Ax_xfHNzaV5p3wZro5d3HUfdtw',
    appId: '1:15051457497:ios:20c83a71319a9cb5d34fc8',
    messagingSenderId: '15051457497',
    projectId: 'flutter-project-01-589db',
    databaseURL: 'https://flutter-project-01-589db-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-01-589db.appspot.com',
    iosClientId: '15051457497-ndun489env50fqck83td91g7up0qhl1o.apps.googleusercontent.com',
    iosBundleId: 'com.kyowa.eclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbbaDq7Ax_xfHNzaV5p3wZro5d3HUfdtw',
    appId: '1:15051457497:ios:20c83a71319a9cb5d34fc8',
    messagingSenderId: '15051457497',
    projectId: 'flutter-project-01-589db',
    databaseURL: 'https://flutter-project-01-589db-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-01-589db.appspot.com',
    iosClientId: '15051457497-ndun489env50fqck83td91g7up0qhl1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );
}
